package:
    type:           library
    name:           php-merchant
    title:          Generalization over Omnipay and Payum
    headline:       PHP merchant library
    keywords:       php, payment, gateway, merchant, omnipay, payum
    namespace:      hiqdev\php\merchant
    description:    |
        [Omnipay](http://omnipay.thephpleague.com/) is a framework agnostic, multi-gateway payment processing library for PHP 5.3+.

        [Payum](http://payum.org/) is payment processing framework for PHP 5.5+.

        This package provides generalized interface for Omnipay and Payum:

        - generalized `purse` and `secret` for gateways
        - generalized `time` and `payer` for responses
        - else?
